version: "3"
env:
  PGM_NAME: firefly
tasks:
  build:
    cmds:
      - cargo fmt
      - cargo build --release --features window-offset,transparent
  run:
    cmds:
      - target/release/$PGM_NAME
  run:bloom:
    cmds:
      - target/release/bloom
  run:bouncing:
    cmds:
      - target/release/bouncing
  run:clock:
    cmds:
      - target/release/clock
  run:cubic:
    cmds:
      - target/release/cubic
  run:firefly:
    cmds:
      - target/release/firefly
  run:flocking:
    cmds:
      - target/release/flocking
  run:followings:
    cmds:
      - target/release/followings
  run:gravity:
    cmds:
      - target/release/gravity
  run:life:
    cmds:
      - target/release/life
  run:mandala:
    cmds:
      - target/release/mandala
  run:menu:
    cmds:
      - target/release/menu
  run:orbit:
    cmds:
      - target/release/orbit
  run:particles:
    cmds:
      - target/release/particles
  run:pong:
    cmds:
      - target/release/pong
  run:rope:
    cmds:
      - target/release/rope
  run:sprites:
    cmds:
      - target/release/sprites
  install:
    deps: [build]
    cmds:
      - cp target/release/$PGM_NAME ~/bin
